apiVersion: apps/v1
kind: Deployment
metadata:
  name: speech-to-text
spec:
  replicas: 1
  selector:
    matchLabels:
      app: speech-to-text
  template:
    metadata:
      labels:
        app: speech-to-text
    spec:
      containers:
        - name: app
          image: masinde70/speech-to-text:latest  # Replace with your Docker image name
          ports:
            - containerPort: 8000
          command: ["uvicorn", "main:app", "--host", "0.0.0.0", "--port", "8000"]
